### ISSUE TITLE
Could not find method yGuard() for arguments ...

### ISSUE THREAD

**Issue by haba-beton** [kordamp/yguard-gradle-plugin#2]
Hi,

i have just try'd to use your yguard gradle plugin but it fails with the following message:

#A problem occurred configuring project ':myproject'.
#> Could not find method yGuard() for arguments [com.yworks:yguard:extension 'yguard' property 'toolVersion'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

#Possible solution:
#- Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

I added your plugin with:

plugins {
  id "org.kordamp.gradle.yguard" version "0.4.0"
}

When i change the version from 0.4.0 to 0.3.0 than it is working and the plugin was found.

best regards

**Comment by aalmiray** [comment]
Bug fixed and new `0.5.0` release is out 😄

**Comment by haba-beton** [comment]
Thank you, now gradle finds the plugin.
